name: climbers_snowflake
version: '1.0.0'
config-version: 2

profile: climbers_snowflake

model-paths: [models]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]

models:
  climbers_snowflake:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
flags:
  require_generic_test_arguments_property: true