-- Run this script manually as ACCOUNTADMIN.
-- Verify the required privilege set on the actual Snowflake trial account before use.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS CLIMBERS_ROLE;

GRANT CREATE DATABASE ON ACCOUNT TO ROLE CLIMBERS_ROLE;

CREATE RESOURCE MONITOR IF NOT EXISTS CLIMBERS_RM
    WITH CREDIT_QUOTA = 5
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS ON 100 PERCENT DO SUSPEND;

CREATE WAREHOUSE IF NOT EXISTS CLIMBERS_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    RESOURCE_MONITOR = CLIMBERS_RM;

GRANT USAGE ON WAREHOUSE CLIMBERS_WH TO ROLE CLIMBERS_ROLE;

CREATE USER IF NOT EXISTS CLIMBERS_SVC
    TYPE = SERVICE
    DEFAULT_ROLE = CLIMBERS_ROLE
    DEFAULT_WAREHOUSE = CLIMBERS_WH
    RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0JhjhlXQ8F+c8tB31fdL9r8A1fAhv3NYhoShmRibXRjfjjgkAJwVHU0FF7VwlO+96R2fJLqpVB961HdVnQ0YZXK7hQi6h+iK0NqXNxZ+B/9e2XcDeLV9tYAbRJfVpboobMBttmk4kQjtbOu8aIL47B8aklGiRRY5pY8VDY3LFrV39SR5qF+P4E6BU4riMGV8OWgT8MUHUV6Q+0q01jDJh69Vize7NGTQgEWIhxGKq0sNjnPx/GD6sHrZqYC4qf/LgI2jnnLFPm9/aQDOpMzFCrb401pBbLrFkTh5VLsXx3ZqCD0+Hz7baEVnJz44cyljWLpomp4yCRQ9zxEsU03NzwIDAQAB';

GRANT ROLE CLIMBERS_ROLE TO USER CLIMBERS_SVC;

CREATE DATABASE IF NOT EXISTS CLIMBERS_DB;

GRANT USAGE ON DATABASE CLIMBERS_DB TO ROLE CLIMBERS_ROLE;
GRANT CREATE SCHEMA ON DATABASE CLIMBERS_DB TO ROLE CLIMBERS_ROLE;

CREATE SCHEMA IF NOT EXISTS CLIMBERS_DB.RAW;
CREATE SCHEMA IF NOT EXISTS CLIMBERS_DB.ANALYTICS;

GRANT ALL PRIVILEGES ON SCHEMA CLIMBERS_DB.RAW TO ROLE CLIMBERS_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA CLIMBERS_DB.ANALYTICS TO ROLE CLIMBERS_ROLE;

CREATE FILE FORMAT IF NOT EXISTS CLIMBERS_DB.RAW.CLIMBERS_CSV_FORMAT
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL', 'null')
    ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE;

CREATE STAGE IF NOT EXISTS CLIMBERS_DB.RAW.CLIMBERS_STAGE
    FILE_FORMAT = CLIMBERS_DB.RAW.CLIMBERS_CSV_FORMAT;

GRANT USAGE ON FILE FORMAT CLIMBERS_DB.RAW.CLIMBERS_CSV_FORMAT TO ROLE CLIMBERS_ROLE;
GRANT READ, WRITE ON STAGE CLIMBERS_DB.RAW.CLIMBERS_STAGE TO ROLE CLIMBERS_ROLE;

GRANT OWNERSHIP ON DATABASE CLIMBERS_DB TO ROLE CLIMBERS_ROLE COPY CURRENT GRANTS;